== Personal sandbox for developing maven plugins

Since most of what I do is release engineering of Eclipse plugins/features/p2 sites, most of what you'll find here will be related to continuous integration builds w/ Jenkins/Hudson of Eclipse plugins/features/sites with Tycho (Maven 3).

No warranty provided or implied. Code's free (as in beer) to do w/ as you'd like.

Licensed under some mix of EPL, WTFPL, and Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0). nickboldt at gmail dot com for more info.

---

== Current plugins

* *hudson-job-sync-plugin* - pull from Jenkins to a local cache of config.xml files, or push those files back to the server. Very handy for batch-editing a collection of jobs using script (eg., using sed to globally replace strings), then making changes to many jobs at once. Works with view names to restrict which jobs will be affected and regular expressions to filter within a given view, so you can pull/push a handful of jobs or update everything. I use this to maintain the >140 jobs needed to build three streams of JBoss Tools and Developer Studio, plus Eclipse WebTools and DataTools.

* *hudson-job-publisher-plugin* - publish (or create) 1 or more new jobs (can override/replace existing jobs, too) via config.xml template file to Hudson/Jenkins server


== Deprecated

A number of old projects have been deleted. See the link:https://github.com/nickboldt/maven-plugins/tree/0.0.2[0.0.2 tag] for details.
